export enum MODELS {
    SITE_SETTING = "SiteSettings",
    PAYMENT_ACCOUNT = "PaymentAccount",
    CHAT_MESSAGE = "ChatMessage",
    ASSET = "Asset",
    ADVERTISEMENT = "Advertisement",
    USER = "User",
    SUBSCRIBER = "Subscriber",
    EMAIL_OTP = "EmailOtp",
    REPORT = "Report",
    REVIEW = "Review",
    TOUR = "Tour",
    TOUR_FAQ = "TourFAQ",
    TOUR_FAQ_VOTE = "TourFAQVote",
    TRAVEL_ARTICLE = "TravelArticle",
    TRAVEL_COMMENT = "TravelComment",
    ADMIN_NOTIFICATION = "AdminNotification",
    USER_NOTIFICATION = "UserNotification",
    GUIDE = "Guide",
    PENDING_GUIDE = "PendingGuide",
    EMPLOYEES = "employees",
    RESET_PASSWORD_REQUEST = "ResetPasswordRequest",
}