export enum EMIT_SOCKET {
    REGISTER_USER = 'REGISTER_USER',
    UNREGISTER_USER = 'UNREGISTER_USER',
}

export enum SOCKET_TRIGGERS {
    SEND_NEW_CHAT_MESSAGE = 'SEND_NEW_CHAT_MESSAGE',
    DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE',
    INCREASE_UNSEEN_MESSAGE_COUNT = 'INCREASE_UNSEEN_MESSAGE_COUNT',
    MARK_AS_SEEN = 'MARK_AS_SEEN',
}
export type SocketTTriggerTypes = `${SOCKET_TRIGGERS}`;

export enum SOCKET_NAMESPACES {
    USER_CHAT = '/user-chat',
    WEBSITE_AGENT_CHAT = '/website-chat'
}
export type SocketNamespaces = `${SOCKET_NAMESPACES}`;